### PR TITLE
translation-server web query: force single result

### PR DESCRIPTION
**Pull request by dhimmel**
Refs https://github.com/zotero/translation-server/issues/65

### CODE REVIEW

**Comment by agitter** [comment]
Because there are so many types of Zotero translators, do you think we need more test cases to help with regression testing on various frequently-used translators?

**Comment by dhimmel** [comment]
> Because there are so many types of Zotero translators, do you think we need more test cases to help with regression testing on various frequently-used translators?

Possibly although I believe translators often include tests in their definitions in https://github.com/zotero/translators. Also I think translation-server has some [tests](https://github.com/zotero/translation-server), although does not appear to use CI. @dstillman, is that correct?

Anyways, I think we should add more translation-server tests here for safety, but shouldn't get carried away, as this is not really the right location. I'd rather help the upstream repositories have the right tests than duplicating them here.

**Comment by dstillman** [comment]
> Also I think translation-server has some tests, although does not appear to use CI. @dstillman, is that correct?

I've just set up Travis for translation-server.

Translator tests are at https://translator-tests.zotero.org/. (These tests were recently reinstated using the new translation server, so there are currently a larger number of failures than there have been at other times, but in many cases it will still fall back to other translators.)

**Comment by agitter** [comment]
> Anyways, I think we should add more translation-server tests here for safety, but shouldn't get carried away, as this is not really the right location. I'd rather help the upstream repositories have the right tests than duplicating them here.

> We should however add regression tests whenever we notice an issue.

Yes, I agree with this.  For instance, GitHub repository URLs and Manubot manuscript URLs are frequently-cited, so those could be good test cases.

**Comment by dhimmel** [comment]
> Yes, I agree with this. For instance, GitHub repository URLs and Manubot manuscript URLs are frequently-cited, so those could be good test cases.

Added in https://github.com/greenelab/manubot/pull/90/commits/c3b3833db2c1f612cdb14d955c7595052f31a3c7.

In https://github.com/greenelab/manubot/pull/90/commits/da32e7c4849fb920b02da88a390f7abf4857045c, I added /search tests for PMIDs, arXiv IDs, and DOIs. Currently, we don't use these, but I thought it'd be good to test to make sure our translation-server instance is working properly.

**Pull request merged**
