### PR TITLE
Configure AppVeyor for Windows CI testing

### PR DESCRIPTION
**Pull request by dhimmel**
Used the following as references:

- https://github.com/ogrisel/python-appveyor-demo/blob/3e6eb8b2f41d0aeaf2cf69105c0cf5aa608b200f/appveyor.yml
- https://github.com/krlmlr/r-appveyor/issues/82
- https://github.com/Tomnl/appveyor-py-test/blob/d17e632c16f7ba571349e2e589e8ac9d031d9596/appveyor.yml

Refs https://github.com/greenelab/manubot/issues/34#issuecomment-392815141

### CODE REVIEW

**Comment by dhimmel** [comment]
This now appears to be working: https://ci.appveyor.com/project/dhimmel/manubot/build/1.0.8/job/g0oop3d6kerm67wm

**Comment by dhimmel** [comment]
> Does it use both .appveyor.yml and appveyor.yml or can we remove .appveyor.yml?

Fixed & kept just `.appveyor.yml` (so it's sorted next to `.travis.yml`).

**Comment by agitter** [comment]
I'm not adept with the AppVeyor project configuration system, but it looks like the badge is linking to a [build](https://ci.appveyor.com/project/dhimmel/manubot/build/job/vm4ykpg8ajgu1hq5) that clones from your fork instead of the `greenelab` repository.  Is that the intended behavior?

Setting up AppVeyor with a [GitHub organization](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization) is not as easy as Travis, so this may be the best option.

**Comment by dhimmel** [comment]
Good catch @agitter. The AppVeyor interface and naming conventions are a bit confusing here.

Previously, I was using AppVeyor on `dhimmel/manubot`, which was the project at https://ci.appveyor.com/project/dhimmel/manubot. Now we're using AppVeyor on `greenelab/manubot` and the project URL is https://ci.appveyor.com/project/dhimmel/manubot-5ft6w.

Basically, AppVeyor uses different accounts, so my dhimmel account can be building greenelab repos. I could go ahead and make a `greenelab` AppVeyor account so the names appear nicer.

With the fix, you can now see the CI integration testing this PR.

**Comment by dhimmel** [comment]
I switched the project to a greenelab appveyor account https://ci.appveyor.com/project/greenelab/manubot

But now it's not showing up on GitHub.

**Comment by dhimmel** [comment]
> But now it's not showing up on GitHub.

Now it is!

**Pull request merged**
